name: panduan_muslim
description: A new Flutter project for Panduan Sholat & Al-Quran.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  google_fonts: ^6.2.1
  audioplayers: ^6.6.0
  shared_preferences: ^2.5.5
  lucide_icons: ^0.257.0
  flutter_svg: ^2.3.0
  flutter_animate: ^4.5.2
  iconsax: ^0.0.8
  remixicon: ^4.9.3
  font_awesome_flutter: ^11.0.0
  flutter_qiblah: ^3.2.0
  geolocator: ^14.0.3
  adhan: ^2.0.0+1
  geocoding: ^4.0.0
  intl: ^0.20.2
  hijri: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
    - assets/logo.png
    - assets/icons/
    - assets/data/
    - assets/data/surat/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
